version: "3"
services:
  authentication-manager:
    image: authentication-manager
    ports:
      - "8090:8090"
    networks:
      - app_net
  api-gateway:
    image: api-gateway
    ports:
      - "8092:8092"
    networks:
      - app_net
  login-ui:
    image: login-ui
    stdin_open: true
    ports:
      - "8094:8094"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
